[package]
name = "viravis"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
colog = "1.3.0"
cpal = "0.15.3"
ctrlc = "3.4.5"
json = "0.12.4"
log = "0.4.25"
realfft = "3.3.0"
rustfft = "6.2.0"
serialport = "4.7.0"
websocket = "0.27.1"
